### PR TITLE
make typescript a peer dependency

### PR DESCRIPTION
**Pull request by jasondibenedetto**

### CODE REVIEW

**Comment by thekevinbrown** [comment]
Resolves #112

**Comment by jasondibenedetto** [comment]
I can get the test passing by installing peer dependencies or adding Typescript as an additional dev dependency, if that helps get this pr through.

**Comment by jasondibenedetto** [comment]
All green now ✅

**Comment by JackCuthbert** [comment]
Thanks for doing this @jasondibenedetto! I've opened up https://github.com/prisma/serverless-plugin-typescript/pull/135 to upgrade all dependencies and include your work.

**Pull request closed without merging**
